CREATE TABLE "atendimentos" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"numero" serial NOT NULL,
	"data_atendimento" date NOT NULL,
	"horario" text NOT NULL,
	"local_abordagem" text NOT NULL,
	"ponto_referencia" text,
	"profissional_responsavel" text NOT NULL,
	"equipe" text,
	"motivo_abordagem" text NOT NULL,
	"motivo_outro" text,
	"nome_completo" text NOT NULL,
	"nome_social" text,
	"data_nascimento" date,
	"nome_mae" text,
	"nome_pai" text,
	"idade" integer,
	"telefone" text,
	"sexo" text,
	"sexo_outro" text,
	"estado_civil" text,
	"naturalidade" text,
	"municipio_origem" text,
	"cpf" text,
	"rg" text,
	"possui_documentacao" text,
	"situacao_atual" text[] DEFAULT '{}' NOT NULL,
	"situacao_atual_outro" text,
	"tempo_situacao" text,
	"rua_tipo" text,
	"rua_motivo" text,
	"rua_quanto_tempo" text,
	"rua_onde_permanece" text,
	"vinculo_preservado" text,
	"vinculo_familiar" text,
	"ref_familiar_nome" text,
	"ref_familiar_telefone" text,
	"ref_familiar_municipio" text,
	"condicao_moradia" text,
	"condicao_moradia_outro" text,
	"saude_condicao" text,
	"uso_medicacao" text,
	"uso_medicacao_qual" text,
	"atendimento_imediato" text,
	"uso_drogas" text,
	"substancias" text[] DEFAULT '{}' NOT NULL,
	"escolaridade" text,
	"possui_renda" text,
	"origem_renda" text,
	"origem_renda_outro" text,
	"valor_renda" numeric,
	"beneficios" text[] DEFAULT '{}' NOT NULL,
	"beneficios_outro" text,
	"numero_nis" text,
	"demandas" text[] DEFAULT '{}' NOT NULL,
	"demandas_outro" text,
	"providencias" text[] DEFAULT '{}' NOT NULL,
	"providencias_outro" text,
	"procedimentos" text[] DEFAULT '{}' NOT NULL,
	"encaminhamentos" text[] DEFAULT '{}' NOT NULL,
	"encaminhamentos_outro" text,
	"necessita_acompanhamento" text,
	"acompanhamento_local" text,
	"responsavel_nome" text,
	"responsavel_cargo" text,
	"assinatura_usuario" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "atendimentos_numero_unique" UNIQUE("numero")
);
--> statement-breakpoint
CREATE TABLE "evolucoes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"atendimento_id" uuid NOT NULL,
	"texto" text NOT NULL,
	"autor_nome" text NOT NULL,
	"autor_cargo" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "veiculo_registros" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"data" date NOT NULL,
	"veiculo" text DEFAULT 'Kombi · DMN 4326' NOT NULL,
	"motorista" text NOT NULL,
	"saida_hora" text NOT NULL,
	"saida_km" integer NOT NULL,
	"saida_local" text NOT NULL,
	"chegada_hora" text,
	"chegada_km" integer,
	"chegada_local" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "evolucoes" ADD CONSTRAINT "evolucoes_atendimento_id_atendimentos_id_fk" FOREIGN KEY ("atendimento_id") REFERENCES "public"."atendimentos"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "atendimentos_data_idx" ON "atendimentos" USING btree ("data_atendimento");--> statement-breakpoint
CREATE INDEX "evolucoes_atendimento_idx" ON "evolucoes" USING btree ("atendimento_id");--> statement-breakpoint
CREATE INDEX "veiculo_registros_data_idx" ON "veiculo_registros" USING btree ("data");